services:
  back:
    container_name: dev-golubator-back
    build:
      context: .
      dockerfile: dev/Dockerfile.back
    volumes:
      - ./back:/app:ro
    logging:
      driver: journald
    restart: always
    networks:
      golubnet:
        aliases:
          - back

  front:
    container_name: dev-golubator-front
    build:
      context: .
      dockerfile: dev/Dockerfile.front
    volumes:
      - ./front:/app
    ports:
      - "4173:4173"
    logging:
      driver: journald
    restart: always
    networks:
      - golubnet

  mongo:
    container_name: dev-golub-mongodb
    image: mongo:8.0-rc
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - golub-mongodb:/data/db
    logging:
      driver: journald
    restart: always
    networks:
      - golubnet

volumes:
  golub-mongodb:
    driver: local

networks:
  golubnet:
    driver: bridge
